export const GET_ERRS='GET_ERRS';

export const LOADING = 'LOADING';

export const SET_OBJECT='SET_OBJECT';
export const SET_TYPE_FUEL='SET_TYPE_FUEL';
export const SET_PASS_ABILITY='SET_PASS_ABILITY';
export const SET_VOLUME='SET_VOLUME';
export const SET_AMOUNT_PEOPLE='SET_AMOUNT_PEOPLE';

export const GET_CURRENT_USER='GET_CURRENT_USER';

export const GET_VEHICLES='GET_VEHICLES';
export const ADD_VEHICLES='ADD_VEHICLES';
export const DELETE_VEHICLE='DELETE_VEHICLE';
export const UPDATE_VEHICLE='UPDATE_VEHICLE';
export const SELECT_VEHICLE='SELECT_VEHICLE';

export const GET_DRIVERS='GET_DRIVERS';
export const ADD_DRIVER='ADD_DRIVER';
export const DELETE_DRIVER='DELETE_DRIVER';
export const UPDATE_DRIVER='UPDATE_DRIVER';
export const SELECT_DRIVER='SELECT_DRIVER';

export const GET_DEFINE_LEVELS='GET_DEFINE_LEVELS';
export const ADD_DEFINE_LEVEL='ADD_DEFINE_LEVEL';
export const DELETE_DEFINE_LEVEL='DELETE_DEFINE_LEVEL';
export const UPDATE_DEFINE_LEVEL='DEFINE_LEVEL';
export const SELECT_DEFINE_LEVEL='SELECT_DEFINE_LEVEL';

export const SET_DISTANCE='SET_DISTANCE';

export const GET_COMMANDS='GET_COMMANDS';
export const ADD_COMMANDS='ADD_COMMANDS';
export const SELECT_COMMAND='SELECT_COMMAND';
export const UPDATE_COMMAND='UPDATE_COMMAND';
export const DELETE_COMMAND='DELETE_COMMAND';


export const GET_MOTOBIKES='GET_MOTOBIKES';
export const ADD_MOTOBIKE='ADD_MOTOBIKE';
export const DELETE_MOTOBIKE='DELETE_MOTOBIKE';
export const UPDATE_MOTOBIKE='MOTOBIKE';
export const SELECT_MOTOBIKE='SELECT_MOTOBIKE';